GET http://localhost:3000/api/test

###
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "email": "chanandrew@gmail.com",
    "password": "password1"
}

###
POST http://localhost:3000/api/login 
Content-Type: application/json

{
    "email": "chanandrew36@gmail.com",
    "password": "password6"
}