module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",

  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",

  INTERNAL_ERROR: "INTERNAL_ERROR",
};
